/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.UUID;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

public class App {

    private static final int CONSOLE_WIDTH = 80; // Adjust as needed for your console width

    private static void printCentered(String text) {
        int padding = (CONSOLE_WIDTH - text.length()) / 2;
        System.out.println(" ".repeat(Math.max(0, padding)) + text);
    }

    private static void printCenteredPrompt(String prompt) {
        int padding = (CONSOLE_WIDTH - prompt.length()) / 2;
        System.out.print(" ".repeat(Math.max(0, padding)) + prompt);
    }

    public static void main(String[] args) {
        printCentered("================================================================================");
        printCentered("Welcome to the Ticket Booking Application!");
        printCentered("================================================================================");
        System.out.println(); // Add a newline for spacing
        
        Scanner sc = new Scanner(System.in);
        int choice = 0;
        UserBookingService userBookingService;

        try {
            userBookingService = new UserBookingService();
        }
        catch (Exception e) {
            System.out.println("Error initializing the booking service: " + e.getMessage());
            sc.close();
            return;
        }

        try {
            while(choice != 7) {
                printCentered("================================================================================");
                System.out.println(); // Add a newline for spacing
                printCentered("Please choose an option:");
                printCentered("1. Sign up");
                printCentered("2. Login");
                printCentered("3. Fetch Bookings");
                printCentered("4. Search Train");
                printCentered("5. Book a Seat");
                printCentered("6. Cancel Booking");
                printCentered("7. Exit");
                printCentered("================================================================================");
                System.out.println(); // Add a newline for spacing before prompt
                printCenteredPrompt("Your choice: ");
                String input = sc.nextLine();
                System.out.println(); // Add a newline after input for spacing
                try {
                    choice = Integer.parseInt(input);
                } catch (NumberFormatException e) {
                    printCentered("Invalid input. Please enter a number between 1 and 7.\n");
                    continue;
                }

                switch (choice) {
                    case 1:
                        printCentered("==================================== Sign Up ====================================");
                        System.out.println(); // Add a newline for spacing
                        printCenteredPrompt("Enter username: ");
                        String nameToSignUp = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        printCenteredPrompt("Enter password: ");
                        String passToSignUp = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        User userToSignUp = new User(nameToSignUp, passToSignUp, UserServiceUtil.hashPassword(passToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                        userBookingService.signUp(userToSignUp);
                        printCentered("User signed up successfully!\n");
                        break;
                    case 2:
                        printCentered("==================================== Login ====================================");
                        System.out.println(); // Add a newline for spacing
                        printCenteredPrompt("Enter username: ");
                        String nameToLogin = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        printCenteredPrompt("Enter password: ");
                        String passToLogin = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        User tempUser = new User(nameToLogin, passToLogin, UserServiceUtil.hashPassword(passToLogin), new ArrayList<>(), "");
                        try {
                            UserBookingService loginService = new UserBookingService(tempUser);
                            if (loginService.loginUser()) {
                                userBookingService = loginService;
                                printCentered("Login successful!\n");
                            } else {
                                printCentered("Invalid username or password.\n");
                            }
                        }
                        catch (Exception e) {
                            printCentered("Error during login: " + e.getMessage() + "\n");
                            continue;
                        }
                        break;
                    case 3:
                        printCentered("=================================== Your Bookings ===================================");
                        System.out.println(); // Add a newline for spacing
                        userBookingService.fetchBooking();
                        printCentered("===================================================================================");
                        System.out.println(); // Add a newline for spacing
                        break;
                    case 4:
                        printCentered("==================================== Search Train ====================================");
                        System.out.println(); // Add a newline for spacing
                        printCenteredPrompt("Enter source station: ");
                        String source = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        printCenteredPrompt("Enter destination station: ");
                        String destination = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        List<Train> trains = userBookingService.getTrains(source, destination);
                        if (trains.isEmpty()) {
                            printCentered("No trains found for the given route.\n");
                        } else {
                            printCentered("Available Trains:");
                            System.out.println(); // Add a newline for spacing
                            int index = 1;
                            for (Train train : trains) {
                                // These prints are formatted in Train.java and Ticket.java now, no need for extra alignment here
                                System.out.println("  " + index + ". Train No: " + train.getTrainNo());
                                System.out.println("      Train Id: " + train.getTrainId());
                                for(Map.Entry<String, String> entry : train.getStationTimes().entrySet()) {
                                    System.out.println("      Station: " + entry.getKey() + ", Time: " + entry.getValue());
                                }
                                index++;
                                System.out.println(); // Add a blank line between trains
                            }
                            printCentered("===================================================================================");
                            System.out.println(); // Add a newline for spacing
                        }
                        break;
                    case 5:
                        printCentered("==================================== Book a Seat ====================================");
                        System.out.println(); // Add a newline for spacing
                        if (userBookingService.getLoggedInUser() == null) {
                            printCentered("Please login to book a seat.\n");
                            break;
                        }
                        printCenteredPrompt("Enter the Train Number (e.g., 12345) to book: ");
                        String trainNoToBook = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing

                        if (trainNoToBook.trim().isEmpty()) {
                            printCentered("Train number cannot be empty. Please try again.\n");
                            break;
                        }

                        printCenteredPrompt("Enter source station for booking: ");
                        String sourceToBook = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        printCenteredPrompt("Enter destination station for booking: ");
                        String destinationToBook = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing
                        
                        userBookingService.bookSeat(userBookingService.getLoggedInUser().getUserId(), trainNoToBook, sourceToBook, destinationToBook);
                        System.out.println(); // Add a newline for spacing
                        break;
                    case 6:
                        printCentered("==================================== Cancel Booking ====================================");
                        System.out.println(); // Add a newline for spacing
                        if (userBookingService.getLoggedInUser() == null) {
                            printCentered("Please login to cancel a booking.\n");
                            break;
                        }
                        printCenteredPrompt("Enter the Booking ID to cancel: ");
                        String bookingIdToCancel = sc.nextLine();
                        System.out.println(); // Add a newline after input for spacing

                        userBookingService.cancelBooking(userBookingService.getLoggedInUser().getUserId(), bookingIdToCancel);
                        System.out.println(); // Add a newline for spacing
                        break;
                    case 7:
                        printCentered("Exiting the application. Goodbye!");
                        printCentered("===============================================================================");
                        return;
                    default:
                        printCentered("Invalid choice. Please try again.\n");
                }
            }
        } finally {
            sc.close();
        }
    }
}
